### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xorond** [mgeeky/tomcatWarDeployer#1]
Hello,

I'd like to add your tool into [ArchStrike](https://github.com/ArchStrike/ArchStrike/) but your tool doesn't have a license.

Is it possible to add one?

Thanks.

**Comment by mgeeky** [comment]
Hello there, 

Thanks for your notice, I'm going to add the license in couple of days. Sure, I will be glad for you to include the tool into your project.

Kind regards,
M.

**Comment by mgeeky** [comment]
LICENSE has been added to the repo, thanks for notice.

**Comment by xorond** [comment]
Thank you, I'll be adding your tool in soon.

**Comment by xorond** [comment]
Added, see [here](https://archstrike.org/news/10018)
