### ISSUE TITLE
run time bug

### ISSUE THREAD

**Issue by sidd-kishan** [mgeeky/tomcatWarDeployer#10]
python tomcatWarDeployer.py -u x.x.x.x -p 8080 -U tomcat -P s3cret

        tomcatWarDeployer (v. 0.4)
	Apache Tomcat auto WAR deployment & launching tool
	Mariusz B. / MGeeky '16-18

Penetration Testing utility aiming at presenting danger of leaving Tomcat misconfigured.
	
Traceback (most recent call last):
  File "tomcatWarDeployer.py", line 1057, in <module>
    main()
  File "tomcatWarDeployer.py", line 878, in main
    (opts, args) = options()
  File "tomcatWarDeployer.py", line 841, in options
    host = extractHostAddress(args[0], opts.url)
IndexError: list index out of range

**Comment by mgeeky** [comment]
Please refer to the help of that program and make sure you launch it correctly. Especially take a look at your usage of `-u` parameter.
