### ISSUE TITLE
mechnaize

### ISSUE THREAD

**Issue by iamtutu** [mgeeky/tomcatWarDeployer#7]
mechanize does not handle non-numeric ports, hence putting the application on a non common http ports (ports outside 80, 8080, 8000) wont allow connection, consider changing the connection script used

**Comment by mgeeky** [comment]
Can you please provide some output regarding the issue you are rising? I did not experience such behavior of `mechanize`: for instance, it works perfectly against **Metasploitable3** port 8282.

**Comment by mgeeky** [comment]
No further details provided.
